### ISSUE TITLE
#update

### ISSUE THREAD

**Issue by Skitelman** [learn-co-curriculum/orm-updating-records#10]
I can't make sense of the update method

```
 def udpate
    sql = "UPDATE songs SET name = ?, album = ? WHERE name = ?"
    DB[:conn].execute(sql, self.name, self.album, self.name)
  end
```

How can we set a new name if we are searching for it by name?

**Comment by SophieDeBenedetto** [comment]
hi @Skitelman, thanks for pointing this out! 

You are absolutely right that the above method just would not work. That is why using name, and not id, is not a good way to update a record. 

Some changes were just made to the reading which should correct that mistake and clarify a few things.
