### ISSUE TITLE
Example is not complete

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/orm-updating-records#19]
"Our Song class has all the methods it needs to create the songs table, insert records into that table and retrieve records from that table."

The .create_table method is missing.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @Samoth112.

We have updated the materials to include `.create_table` and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
