### ISSUE TITLE
Small typo: "a" instead of "an"

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/orm-updating-records#21]
Last line should read "a" method. 

********
"This code is almost exactly the same as the code we used to update the album of the first song. The only difference is in the particular attribute we wanted to update. In the first case, we were updating the album. In this case, we updated the name. Repetitious code has a smell. Let's extract this functionality of updating a record into an method, #update."

**Comment by maxwellbenton** [comment]
Fixed! Thanks for spotting this and letting us know, @ccklight!
